## Task 01 - Image Analysis

Name: Felipe Pereira

In [1]:
import sys
sys.path.append('/home/felipe/python_envs/env_felipe/lib/python3.8/site-packages')

In [2]:
# Importing libraries that were used in this notebook
import cv2
import glob, os
import numpy as np

from PIL import Image
from sklearn.datasets import load_sample_image
from sklearn.feature_extraction import image

### Dataset composition

In [5]:
for file_name in os.listdir('plates/originals/'):
    
    if file_name.endswith("0200.png"):
    
        # Reading image
        image = cv2.imread('plates/originals/' + file_name,cv2.IMREAD_GRAYSCALE)

        # Setting initial patch center    
        width_img=50

        # Setting final dimensions
        last_height_img=225
        last_width_img=325

        # Setting stride
        stride_pixels=15

        # Defining patch number
        patch_number=1

        while width_img <= last_width_img:

            # Setting initial patch center    
            height_img=50 

            while height_img <= last_height_img:                   

                # Defining some values
                patch_center = np.array([height_img, width_img])        
                patch_scale = 0.38

                # Calc patch position and extract the patch
                smaller_dim = np.min(image.shape[0:2])
                patch_size = int(patch_scale * smaller_dim)
                patch_x = int(patch_center[0] - patch_size / 2.)
                patch_y = int(patch_center[1] - patch_size / 2.)
                patch_image = image[patch_x:patch_x+patch_size, patch_y:patch_y+patch_size]

                # Transforming gray scalte to bgr
                rgb_patch = cv2.cvtColor(patch_image, cv2.COLOR_GRAY2BGR)

                # Transforming bgr to ycrcb
                ycrcb_patch = cv2.cvtColor(rgb_patch, cv2.COLOR_BGR2YCrCb)

                # Writing output            
                patch_output = file_name.replace('.png','') + '_p' + str(patch_number) + '.png'                
                cv2.imwrite('output/' + patch_output,ycrcb_patch)

                # Updating height loop var
                height_img = height_img + stride_pixels
                patch_number = patch_number + 1

                # Debugging                
                #print('Height: {}'.format(height_img))
                #print('Width: {}'.format(width_img))
                #print('Patch Number: {}'.format(patch_number))

            # Updating width loop var
            width_img = width_img + stride_pixels       
        
        # Looping through files
        print('Processed file: {}'.format(file_name))

Processed file: orig_0200.png


### Batch Normalization

In [9]:
for file_name in os.listdir('plates/originals/'):
           
    if file_name.endswith("0200.png"):
    
        # Reading image
        image = cv2.imread('plates/originals/' + file_name,cv2.IMREAD_GRAYSCALE)

        # Setting initial patch center    
        width_img=50

        # Setting final dimensions
        last_height_img=225
        last_width_img=325
        #last_height_img=75
        #last_width_img=50

        # Setting stride
        stride_pixels=15

        # Defining patch number
        patch_number=1

        while width_img <= last_width_img:

            # Setting initial patch center    
            height_img=50 

            while height_img <= last_height_img:                   

                # Defining some values
                patch_center = np.array([height_img, width_img])        
                patch_scale = 0.38

                # Calc patch position and extract the patch
                smaller_dim = np.min(image.shape[0:2])
                patch_size = int(patch_scale * smaller_dim)
                patch_x = int(patch_center[0] - patch_size / 2.)
                patch_y = int(patch_center[1] - patch_size / 2.)
                patch_image = image[patch_x:patch_x+patch_size, patch_y:patch_y+patch_size]

                # Transforming gray scalte to bgr
                rgb_patch = cv2.cvtColor(patch_image, cv2.COLOR_GRAY2BGR)

                # Transforming bgr to ycrcb
                ycrcb_patch = cv2.cvtColor(rgb_patch, cv2.COLOR_BGR2YCrCb)
        
                # Transforming image into an array
                #c1_array = np.asarray(rgb_patch[:,:,0])
                #c2_array = np.asarray(rgb_patch[:,:,1])
                #c2_array = np.asarray(rgb_patch[:,:,2])
                
                c1_array = np.asarray(ycrcb_patch[:,:,0])
                c2_array = np.asarray(ycrcb_patch[:,:,1])
                c3_array = np.asarray(ycrcb_patch[:,:,2])
        
                # Getting array metrics        
                #print('Channel 1 - Metrics:')
                #print('Sum of pixels: {}'.format(np.sum(c1_array)))
                #print('Mean of pixels: {}'.format(np.mean(c1_array)))
                #print('Std of pixels: {}'.format(np.std(c1_array)))
                #print('Array shape: {}'.format(c1_array.shape))
                #print(' ')
                #print('Channel 2 - Metrics:')
                #print('Sum of pixels: {}'.format(np.sum(c2_array)))
                #print('Mean of pixels: {}'.format(np.mean(c2_array)))
                #print('Std of pixels: {}'.format(np.std(c2_array)))
                #print(' ')
                #print('Channel 3 - Metrics:')
                #print('Sum of pixels: {}'.format(np.sum(c3_array)))
                #print('Mean of pixels: {}'.format(np.mean(c3_array)))
                #print('Std of pixels: {}'.format(np.std(c3_array)))
                #print(' ')
                
                # Normalization
                c1_array_mm = c1_array - c1_array.mean(axis=1, keepdims=True)
                c1_array_normalized = c1_array_mm / c1_array.std(axis=1, keepdims=True)
                
                c2_array_mm = c2_array - c2_array.mean(axis=1, keepdims=True)
                c2_array_normalized = c2_array_mm / c2_array.std(axis=1, keepdims=True)
                
                c3_array_mm = c3_array - c3_array.mean(axis=1, keepdims=True)
                c3_array_normalized = c3_array_mm / c1_array.std(axis=1, keepdims=True)
                
                # Getting array metrics  
                #print('Channel 1 Normalized - Metrics:')
                #print('Sum of pixels: {}'.format(np.sum(c1_array_normalized)))
                #print('Mean of pixels: {}'.format(np.mean(c1_array_normalized)))
                #print('Std of pixels: {}'.format(np.std(c1_array_normalized)))
                #print('Array shape: {}'.format(c1_array_normalized.shape))
                #print(' ')
                #print('Channel 2 Normalized - Metrics:')
                #print('Sum of pixels: {}'.format(np.sum(c2_array_normalized)))
                #print('Mean of pixels: {}'.format(np.mean(c2_array_normalized)))
                #print('Std of pixels: {}'.format(np.std(c2_array_normalized)))
                #print(' ')
                #print('Channel 3 Normalized - Metrics:')
                #print('Sum of pixels: {}'.format(np.sum(c3_array_normalized)))
                #print('Mean of pixels: {}'.format(np.mean(c3_array_normalized)))
                #print('Std of pixels: {}'.format(np.std(c3_array_normalized)))
                #print(' ')
                
                # Writing output            
                patch_output = file_name.replace('.png','') + '_p' + str(patch_number) + '_c1_normalized.png'                
                Image.fromarray(c1_array_normalized).convert('RGB').save('output/' + patch_output)
                
                patch_output = file_name.replace('.png','') + '_p' + str(patch_number) + '_c2_normalized.png'                
                Image.fromarray(c2_array_normalized).convert('RGB').save('output/' + patch_output)
                
                patch_output = file_name.replace('.png','') + '_p' + str(patch_number) + '_c3_normalized.png'                
                Image.fromarray(c3_array_normalized).convert('RGB').save('output/' + patch_output)
                
                #cv2.imwrite('output/' + patch_output,gr_im)                
                
                # Updating height loop var
                height_img = height_img + stride_pixels                                
                patch_number = patch_number + 1

            # Updating width loop var
            width_img = width_img + stride_pixels       
        
        # Looping through files
        print('Processed file: {}'.format(file_name))

<ipython-input-9-5d7ab568ad68>:79: RuntimeWarning: invalid value encountered in true_divide
  c2_array_normalized = c2_array_mm / c2_array.std(axis=1, keepdims=True)


Processed file: orig_0200.png


### Random Kernels

In [18]:
# Creating random matrices
kernel_01 = np.random.rand(3,3)
kernel_01_mean = kernel_01 - kernel_01.mean(axis=1, keepdims=True)

kernel_02 = np.random.rand(3,3)
kernel_02_mean = kernel_02 - kernel_02.mean(axis=1, keepdims=True)

kernel_03 = np.random.rand(3,3)
kernel_03_mean = kernel_03 - kernel_03.mean(axis=1, keepdims=True)

In [20]:
kernel_01

array([[0.21980778, 0.78481598, 0.48137923],
       [0.73919692, 0.37351633, 0.08824112],
       [0.69669695, 0.32508871, 0.40736512]])

In [19]:
kernel_01_mean

array([[-0.27552655,  0.28948165, -0.0139551 ],
       [ 0.3388788 , -0.02680179, -0.31207701],
       [ 0.22031336, -0.15129488, -0.06901847]])

In [12]:
kernel_02

array([[0.70320468, 0.6859957 , 0.14971025],
       [0.68363737, 0.86322721, 0.19225785],
       [0.20189084, 0.78267423, 0.11192871]])

In [13]:
kernel_03

array([[0.56824472, 0.31371426, 0.87588369],
       [0.19023029, 0.38800759, 0.25702264],
       [0.68979579, 0.41636415, 0.73928157]])

In [14]:
kernel_sobel = np.array([[-1, 0, -1], [-2, 0, 2], [-1, 0, 1]])
kernel_sobel

array([[-1,  0, -1],
       [-2,  0,  2],
       [-1,  0,  1]])

### Convolution

In [15]:
def convolve2D(image, kernel, padding=0, strides=1):
    # Cross Correlation
    kernel = np.flipud(np.fliplr(kernel))

    # Gather Shapes of Kernel + Image + Padding
    xKernShape = kernel.shape[0]
    yKernShape = kernel.shape[1]
    xImgShape = image.shape[0]
    yImgShape = image.shape[0]

    # Shape of Output Convolution
    xOutput = int(((xImgShape - xKernShape + 2 * padding) / strides) + 1)
    yOutput = int(((yImgShape - yKernShape + 2 * padding) / strides) + 1)
    output = np.zeros((xOutput, yOutput))

    # Apply Equal Padding to All Sides
    if padding != 0:
        imagePadded = np.zeros((image.shape[0] + padding*2, image.shape[1] + padding*2))
        imagePadded[int(padding):int(-1 * padding), int(padding):int(-1 * padding)] = image
        print(imagePadded)
    else:
        imagePadded = image

    # Iterate through image
    for y in range(image.shape[1]):
        # Exit Convolution
        if y > image.shape[1] - yKernShape:
            break
        # Only Convolve if y has gone down by the specified Strides
        if y % strides == 0:
            for x in range(image.shape[0]):
                # Go to next row once kernel is out of bounds
                if x > image.shape[0] - xKernShape:
                    break
                try:
                    # Only Convolve if x has moved by the specified Strides
                    if x % strides == 0:
                        output[x, y] = (kernel * imagePadded[x: x + xKernShape, y: y + yKernShape]).sum()
                except:
                    break

    return output

In [21]:
for file_name in os.listdir('plates/originals/'):
           
    if file_name.endswith("0200.png"):
    
        # Reading image
        image = cv2.imread('plates/originals/' + file_name,cv2.IMREAD_GRAYSCALE)

        # Setting initial patch center    
        width_img=50

        # Setting final dimensions
        last_height_img=225
        last_width_img=325
        #last_height_img=75
        #last_width_img=50

        # Setting stride
        stride_pixels=15

        # Defining patch number
        patch_number=1

        while width_img <= last_width_img:

            # Setting initial patch center    
            height_img=50 

            while height_img <= last_height_img:                   

                # Defining some values
                patch_center = np.array([height_img, width_img])        
                patch_scale = 0.38

                # Calc patch position and extract the patch
                smaller_dim = np.min(image.shape[0:2])
                patch_size = int(patch_scale * smaller_dim)
                patch_x = int(patch_center[0] - patch_size / 2.)
                patch_y = int(patch_center[1] - patch_size / 2.)
                patch_image = image[patch_x:patch_x+patch_size, patch_y:patch_y+patch_size]

                # Transforming gray scalte to bgr
                rgb_patch = cv2.cvtColor(patch_image, cv2.COLOR_GRAY2BGR)

                # Transforming bgr to ycrcb
                ycrcb_patch = cv2.cvtColor(rgb_patch, cv2.COLOR_BGR2YCrCb)
        
                # Transforming image into an array
                c1_array = np.asarray(ycrcb_patch[:,:,0])
                c2_array = np.asarray(ycrcb_patch[:,:,1])
                c2_array = np.asarray(ycrcb_patch[:,:,2])
                
                # Convolutions - Random
                conv_01 = convolve2D(c1_array,kernel_01_mean)
                conv_02 = convolve2D(c2_array,kernel_02_mean)
                conv_03 = convolve2D(c3_array,kernel_03_mean)
                
                # Convolutions - Sobel
                #conv_sobel_01 = convolve2D(c1_array,kernel_sobel)
                #conv_sobel_02 = convolve2D(c2_array,kernel_sobel)
                #conv_sobel_03 = convolve2D(c3_array,kernel_sobel)                
                
                # Writing output            
                patch_output = file_name.replace('.png','') + '_p' + str(patch_number) + '_conv_01.png'                
                Image.fromarray(conv_01).convert('RGB').save('output/' + patch_output)
                
                patch_output = file_name.replace('.png','') + '_p' + str(patch_number) + '_conv_02.png'                
                Image.fromarray(conv_02).convert('RGB').save('output/' + patch_output)
                
                patch_output = file_name.replace('.png','') + '_p' + str(patch_number) + '_conv_03.png'                
                Image.fromarray(conv_03).convert('RGB').save('output/' + patch_output)                        
                
                # Updating height loop var
                height_img = height_img + stride_pixels                                
                patch_number = patch_number + 1

            # Updating width loop var
            width_img = width_img + stride_pixels       
        
        # Looping through files
        print('Processed file: {}'.format(file_name))

Processed file: orig_0200.png


### ReLu

In [22]:
def relu(X):
   return np.maximum(0,X)

In [24]:
for file_name in os.listdir('plates/originals/'):
           
    if file_name.endswith("0200.png"):
    
        # Reading image
        image = cv2.imread('plates/originals/' + file_name,cv2.IMREAD_GRAYSCALE)

        # Setting initial patch center    
        width_img=50

        # Setting final dimensions
        last_height_img=225
        last_width_img=325
        #last_height_img=75
        #last_width_img=50

        # Setting stride
        stride_pixels=15

        # Defining patch number
        patch_number=1

        while width_img <= last_width_img:

            # Setting initial patch center    
            height_img=50 

            while height_img <= last_height_img:                   

                # Defining some values
                patch_center = np.array([height_img, width_img])        
                patch_scale = 0.38

                # Calc patch position and extract the patch
                smaller_dim = np.min(image.shape[0:2])
                patch_size = int(patch_scale * smaller_dim)
                patch_x = int(patch_center[0] - patch_size / 2.)
                patch_y = int(patch_center[1] - patch_size / 2.)
                patch_image = image[patch_x:patch_x+patch_size, patch_y:patch_y+patch_size]

                # Transforming gray scalte to bgr
                rgb_patch = cv2.cvtColor(patch_image, cv2.COLOR_GRAY2BGR)

                # Transforming bgr to ycrcb
                ycrcb_patch = cv2.cvtColor(rgb_patch, cv2.COLOR_BGR2YCrCb)
        
                # Transforming image into an array
                c1_array = np.asarray(ycrcb_patch[:,:,0])
                c2_array = np.asarray(ycrcb_patch[:,:,1])
                c2_array = np.asarray(ycrcb_patch[:,:,2])
                
                # Convolutions - Sobel
                conv_sobel_01 = convolve2D(c1_array,kernel_01_mean)
                conv_sobel_02 = convolve2D(c2_array,kernel_02_mean)
                conv_sobel_03 = convolve2D(c3_array,kernel_03_mean)                
                           
                # ReLu
                relu_01 = relu(conv_sobel_01)
                relu_02 = relu(conv_sobel_02)
                relu_03 = relu(conv_sobel_03)                
                
                # Writing output            
                patch_output = file_name.replace('.png','') + '_p' + str(patch_number) + '_relu_01.png'                
                Image.fromarray(relu_01).convert('RGB').save('output/' + patch_output)
                
                patch_output = file_name.replace('.png','') + '_p' + str(patch_number) + '_relu_02.png'                
                Image.fromarray(relu_02).convert('RGB').save('output/' + patch_output)
                
                patch_output = file_name.replace('.png','') + '_p' + str(patch_number) + '_relu_03.png'                
                Image.fromarray(relu_03).convert('RGB').save('output/' + patch_output)                        
                
                # Updating height loop var
                height_img = height_img + stride_pixels                                
                patch_number = patch_number + 1

            # Updating width loop var
            width_img = width_img + stride_pixels       
        
        # Looping through files
        print('Processed file: {}'.format(file_name))

Processed file: orig_0200.png
